name: gcc_ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gcc_ci:

    runs-on: [make, gcc, riscv-gcc]

    steps:
    - uses: actions/checkout@v4

    - name: Simulate
      shell: bash
      run: |
        make CI
